version: '2.2'

services:
  bluetooth-presence-monitor:
    # image: dotwee/bluetooth-presence-monitor:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bluetooth-presence-monitor
    volumes:
      - ./config:/config:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      # optionally bind your host's time config readonly
      # or use the TZ environment variable
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    network_mode: host # bluetooth
    #cpus: 0.4
    #mem_limit: 32M
    restart: always
    cap_add:
      - NET_ADMIN
    #command: ["bash", "/monitor/monitor.sh", "-V", "-r", "-a", "-b", "-D", "/config"]
    # optionally set your timezone (UTC is used by default)
    # environment:
    #   - TZ="Europe/Berlin"