name: build and publish docker image

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
          
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: build & push the image to docker hub
        run: |
          docker buildx build --push \
            --tag dotwee/bluetooth-presence-monitor:latest \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .
      
      - name: login to github packages
        run: echo "${{ secrets.GH_REGISTRY_TOKEN }}" | docker login -u "${{ secrets.GH_REGISTRY_USERNAME }}" --password-stdin

      - name: build & push the image to github docker registry
        run: |
          docker buildx build --push \
            --tag docker.pkg.github.com/dotwee/docker-bluetooth-presence-monitor/bluetooth-presence-monitor:latest \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .